/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Editor.form;

/**
 *
 * @author Robert A. Cherry
 */
public class ImageInfoPanel extends javax.swing.JPanel {

    private ImageInfoPanel() {
        //
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        settingJPanel = new javax.swing.JPanel();
        locationJField = new javax.swing.JTextField();
        locationJLabel = new javax.swing.JLabel();
        pluginJLabel = new javax.swing.JLabel();
        pluginJTextField = new javax.swing.JTextField();
        widthJLabel = new javax.swing.JLabel();
        imageJButton = new javax.swing.JButton();
        heightJLabel = new javax.swing.JLabel();
        idJLabel1 = new javax.swing.JLabel();
        nameJLabel1 = new javax.swing.JLabel();
        referenceJField = new javax.swing.JTextField();
        nameJField = new javax.swing.JTextField();
        displayJField = new javax.swing.JTextField();
        displayJLabel1 = new javax.swing.JLabel();
        generateJButton = new javax.swing.JButton();
        widthJField = new javax.swing.JTextField();
        heightJField = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(275, 240));
        setPreferredSize(new java.awt.Dimension(275, 240));

        settingJPanel.setMinimumSize(new java.awt.Dimension(255, 218));
        settingJPanel.setPreferredSize(new java.awt.Dimension(255, 218));
        java.awt.GridBagLayout settingJPanelLayout = new java.awt.GridBagLayout();
        settingJPanelLayout.columnWidths = new int[] {0, 5, 0};
        settingJPanelLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        settingJPanel.setLayout(settingJPanelLayout);

        locationJField.setEnabled(false);
        locationJField.setMaximumSize(new java.awt.Dimension(140, 22));
        locationJField.setMinimumSize(new java.awt.Dimension(140, 22));
        locationJField.setPreferredSize(new java.awt.Dimension(140, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        settingJPanel.add(locationJField, gridBagConstraints);

        locationJLabel.setText("Image Location:");
        locationJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        locationJLabel.setMaximumSize(new java.awt.Dimension(104, 22));
        locationJLabel.setMinimumSize(new java.awt.Dimension(104, 22));
        locationJLabel.setPreferredSize(new java.awt.Dimension(104, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        settingJPanel.add(locationJLabel, gridBagConstraints);

        pluginJLabel.setText("Part of Package:");
        pluginJLabel.setMaximumSize(new java.awt.Dimension(104, 22));
        pluginJLabel.setMinimumSize(new java.awt.Dimension(104, 22));
        pluginJLabel.setPreferredSize(new java.awt.Dimension(104, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        settingJPanel.add(pluginJLabel, gridBagConstraints);

        pluginJTextField.setEnabled(false);
        pluginJTextField.setMaximumSize(new java.awt.Dimension(140, 22));
        pluginJTextField.setMinimumSize(new java.awt.Dimension(140, 22));
        pluginJTextField.setPreferredSize(new java.awt.Dimension(140, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        settingJPanel.add(pluginJTextField, gridBagConstraints);

        widthJLabel.setText("Image Width :");
        widthJLabel.setEnabled(false);
        widthJLabel.setMaximumSize(new java.awt.Dimension(104, 22));
        widthJLabel.setMinimumSize(new java.awt.Dimension(104, 22));
        widthJLabel.setPreferredSize(new java.awt.Dimension(104, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        settingJPanel.add(widthJLabel, gridBagConstraints);

        imageJButton.setText("Change Source Image");
        imageJButton.setMaximumSize(new java.awt.Dimension(140, 26));
        imageJButton.setMinimumSize(new java.awt.Dimension(140, 26));
        imageJButton.setPreferredSize(new java.awt.Dimension(140, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        settingJPanel.add(imageJButton, gridBagConstraints);

        heightJLabel.setText("Image Height:");
        heightJLabel.setEnabled(false);
        heightJLabel.setMaximumSize(new java.awt.Dimension(104, 22));
        heightJLabel.setMinimumSize(new java.awt.Dimension(104, 22));
        heightJLabel.setPreferredSize(new java.awt.Dimension(104, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        settingJPanel.add(heightJLabel, gridBagConstraints);

        idJLabel1.setText("Reference ID:");
        idJLabel1.setMaximumSize(new java.awt.Dimension(104, 22));
        idJLabel1.setMinimumSize(new java.awt.Dimension(104, 22));
        idJLabel1.setPreferredSize(new java.awt.Dimension(104, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        settingJPanel.add(idJLabel1, gridBagConstraints);

        nameJLabel1.setText("Reference Name:");
        nameJLabel1.setMaximumSize(new java.awt.Dimension(104, 22));
        nameJLabel1.setMinimumSize(new java.awt.Dimension(104, 22));
        nameJLabel1.setPreferredSize(new java.awt.Dimension(104, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        settingJPanel.add(nameJLabel1, gridBagConstraints);

        referenceJField.setToolTipText("");
        referenceJField.setMaximumSize(new java.awt.Dimension(140, 22));
        referenceJField.setMinimumSize(new java.awt.Dimension(140, 22));
        referenceJField.setPreferredSize(new java.awt.Dimension(140, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        settingJPanel.add(referenceJField, gridBagConstraints);

        nameJField.setMaximumSize(new java.awt.Dimension(140, 22));
        nameJField.setMinimumSize(new java.awt.Dimension(140, 22));
        nameJField.setPreferredSize(new java.awt.Dimension(140, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        settingJPanel.add(nameJField, gridBagConstraints);

        displayJField.setMaximumSize(new java.awt.Dimension(140, 22));
        displayJField.setMinimumSize(new java.awt.Dimension(140, 22));
        displayJField.setPreferredSize(new java.awt.Dimension(140, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        settingJPanel.add(displayJField, gridBagConstraints);

        displayJLabel1.setText("Display Name:");
        displayJLabel1.setMaximumSize(new java.awt.Dimension(104, 22));
        displayJLabel1.setMinimumSize(new java.awt.Dimension(104, 22));
        displayJLabel1.setPreferredSize(new java.awt.Dimension(104, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        settingJPanel.add(displayJLabel1, gridBagConstraints);

        generateJButton.setText("Generate ID's");
        generateJButton.setMaximumSize(new java.awt.Dimension(104, 26));
        generateJButton.setMinimumSize(new java.awt.Dimension(104, 26));
        generateJButton.setPreferredSize(new java.awt.Dimension(104, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, -2, 0, 0);
        settingJPanel.add(generateJButton, gridBagConstraints);

        widthJField.setEditable(false);
        widthJField.setMaximumSize(new java.awt.Dimension(140, 22));
        widthJField.setMinimumSize(new java.awt.Dimension(140, 22));
        widthJField.setPreferredSize(new java.awt.Dimension(140, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        settingJPanel.add(widthJField, gridBagConstraints);

        heightJField.setEditable(false);
        heightJField.setMaximumSize(new java.awt.Dimension(140, 22));
        heightJField.setMinimumSize(new java.awt.Dimension(140, 22));
        heightJField.setPreferredSize(new java.awt.Dimension(140, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        settingJPanel.add(heightJField, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settingJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settingJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField displayJField;
    private javax.swing.JLabel displayJLabel1;
    private javax.swing.JButton generateJButton;
    private javax.swing.JTextField heightJField;
    private javax.swing.JLabel heightJLabel;
    private javax.swing.JLabel idJLabel1;
    private javax.swing.JButton imageJButton;
    private javax.swing.JTextField locationJField;
    private javax.swing.JLabel locationJLabel;
    private javax.swing.JTextField nameJField;
    private javax.swing.JLabel nameJLabel1;
    private javax.swing.JLabel pluginJLabel;
    private javax.swing.JTextField pluginJTextField;
    private javax.swing.JTextField referenceJField;
    private javax.swing.JPanel settingJPanel;
    private javax.swing.JTextField widthJField;
    private javax.swing.JLabel widthJLabel;
    // End of variables declaration//GEN-END:variables
}
